### ISSUE TITLE
Can you help?

### ISSUE THREAD

**Issue by mmehdi** [Charles-IV/android_device_tcl_4034X#5]
Hi,
We are trying to run LineageOS on Alcatel Pixi 4 4034. Are you interested to work with us? (paid), w are based in London.
Let me know please.

Thanks

**Comment by Charles-IV** [comment]
Thank you very much for the offer. Unfortunately I am not currently available.
I can try to help or give pointers (in a few months time) for you to do it yourselves, but otherwise I can't help much (plus I've already kinda given up on this, and can't test it myself).
You may be able to see another of my repos (same name with a -los on the end) which I forked from @mishurov with the hope of getting los to work. He may not have the exact same device, but he was the one actually porting the ROMs, and I was just porting them to this device. Maybe he could help?

If you haven't bought any devices yet, I would recommend reconsidering and choosing another device, possibly one with official LineageOS support.

**Comment by mmehdi** [comment]
Thanks for you reply. Actually we are not keen on running los, we just want to fix the bugs (bluetooth, sim) etc and run either los or cm and add our own system services as part of OS. This phone fits into one of our existing products so we are really interested to use this particular phone. We are happy to send you a device if that could help.
I have managed to run the cm on the phone using your code but the sim and bluetooth bug is there.

**Comment by mishurov** [comment]
@mmehdi, yeah, sim was a hell of a problem, this patch for the original source code for LineageOS 13 helped me to fix ril.
https://github.com/mishurov/android_device_TCL_5010D/blob/cm-13.0/patches/ril.patch

I can't say anything about bluetooth in your case, it depends on libraries from the stock rom and a device tree.

P.S. Excuse me for interruption

**Comment by mmehdi** [comment]
@mishurov thank you, I will give it a try and get back to you. No worries for interruption!

**Comment by mmehdi** [comment]
@mishurov Hi, I tried your ril patch and it seems to pick up the sim card now. But the phone app is not stable. Can I contact you by email?

**Comment by mishurov** [comment]
@mmehdi Hi, ammishurov@gmail.com

**Comment by Charles-IV** [comment]
glad you were able to help, closing.

**Comment by mishurov** [comment]
Well, I moved the sources of LineageOS to the phone. But  I don't know a toss about AOSP.
